/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    Toast: typeof import('./../components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./../components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./../components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./../components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./../components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./../components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./../components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./../components/ui/toast/ToastViewport.vue')['default']
  }
}
